<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-26 17:18

$extensionPath = t3lib_extMgm::extPath('lth_feedit_simple');
return array(
    'lth_feeditsimple_adminpanel' => $extensionPath . 'view/class.lth_feeditsimple_adminpanel.php',
    'lth_feeditsimple_menu' => $extensionPath . 'view/class.lth_feeditsimple_menu.php',
    'lth_feeditsimple_newcontentelements' => $extensionPath . 'view/class.lth_feeditsimple_newcontentelements.php',
);